SELECT 
    DATE_FORMAT(LW_DOCUMENT.LAST_DATE_TIME,
            '%Y-%m-%d %k') AS HOUR,
    LW_DOCUMENT.DESTINATION_ID,
    LW_DOCUMENT.STATUS,
    COUNT(*) AS COUNT
FROM
    LW_DOCUMENT
GROUP BY DATE_FORMAT(LW_DOCUMENT.LAST_DATE_TIME,
        '%Y-%m-%d %k') , LW_DOCUMENT.DESTINATION_ID , LW_DOCUMENT.STATUS
ORDER BY LW_DOCUMENT.LAST_DATE_TIME DESC , LW_DOCUMENT.DESTINATION_ID;