SELECT 
    LW_DOCUMENT.*,
    LW_MESSAGE.*,
    GREATEST(LW_DOCUMENT.LAST_DATE_TIME,
            LW_MESSAGE.LAST_DATE_TIME) AS OVERALL_LAST_DATE_TIME,
    CASE
        WHEN
            GREATEST(LW_DOCUMENT.LAST_DATE_TIME,
                    LW_MESSAGE.LAST_DATE_TIME) = LW_DOCUMENT.LAST_DATE_TIME
        THEN
            LW_DOCUMENT.STATUS
        ELSE LW_MESSAGE.STATUS
    END AS OVERALL_STATUS
FROM
    LW_DOCUMENT
        INNER JOIN
    LW_MESSAGE ON LW_DOCUMENT.OUT_WFID = LW_MESSAGE.WFID;